### ISSUE TITLE
Why create your own server?

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#13]
Just thinking out loud here, but I don't understand why everybody seems to be trying to make their own server and load the models themselves.  This oobabooga (https://github.com/oobabooga) repository has clearly figured it all out and they've got everything loading and running on the GPU and they even have an API.  When I look at the AutoGPT and BabyAGI repos, they are all struggling to get local llama support and it makes no sense to me.  Why wouldn't everybody just assume oobabooga as the back-end model serving api to replace all the OpenAI API calls?  I mean, aren't we all just trying to have a drop in replacement for the OpenAI api?

I see that someone is also trying to do this:  https://github.com/Significant-Gravitas/Auto-GPT/issues/348#issuecomment-1501506554

But nobody is going to beat what oobabooga has setup right now.  It's super fast and it makes everything really easy, including downloading and managing the models.  I see people copying the download model code as well, which is insane because you've got a great UI to do it in oobabooga.  

Honest question here, but why wouldn't you plug into all that so you could focus on the actual langchain and agent aspect of this project?  What is preventing everybody from just using oobabooga?  Is it the embedding api?  I don't know, after using oobabooga and seeing how far along it is I just don't get why other projects like AutoGPT don't have this as an option.

**Comment by paolorechia** [comment]
It’s an interesting question, to be fair I did not ever use oobagooba’s
repository to assess how good it would integrate with langchain.

I think one point is that everything is quite new and moving fast, so we’re
not aware of everything out there when starting out.

For instance, I initially tried using the FastChat web server, but their
web server did not behave like what I needed which made me roll my own
version to use with langchain.

Back then I wasn’t even using quantized models yet, just wanted to use
Vicuna with langchain.

Once I sorted that out and shared this repo, people started asking about
quantized models so I added some support, also to use them myself.

It could well be that the way I did is not the best option today and that a
rewrite of the server layer is a good idea (e.g., by reusing others work to
support more models / environments). I think I saw a repo that exposed LLM
web servers through Docker, maybe that’s an interesting option to use here.

Over time we might see everyone converging into an easy to use solution.

Another point is that most of us are doing this on free time, so we really
just do what seems more fun or in a way that provides the best learning
experience for us (but not necessarily for everyone out there). This is
true in my case, for instance.

I hope that clarifies why the landscape of local LLMs are so confusing.


TestUser ***@***.***> schrieb am So. 30. Apr. 2023 um 13:55:

**Comment by paolorechia** [comment]
I skimmed over the `api-example` from oobabooga, it seems quite configurable, so I don't see why we could not integrate that with langchain.

`https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py`

I'll try to install the `oobabooga` text generation web UI here and give it a try.

**Comment by paolorechia** [comment]
Also, I didn't answer one question: never seen the embeddings from Vicuna available elsewhere, but the results were quite inferior to sentence transformers, so I don't think it makes sense to maintain it :)

**Comment by paolorechia** [comment]
@unoriginalscreenname 

It seems promising, I'm almost finishing integrating it:

https://github.com/paolorechia/learn-langchain/pull/14

However, when I tried this model (https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g) with TextGeneration UI, I got gibberish output, like mentioned in Bloke model card (since the TextGeneration UI uses an older version of the library).

How did you load it successfully on TextGenerationUI

**Comment by paolorechia** [comment]
Here's a sample image of what I mean:
![image](https://user-images.githubusercontent.com/5386983/235375796-b81b49fc-145f-4924-ad28-3cc3088924b2.png)

**Comment by paolorechia** [comment]
In the UI worked fine with HF models. Just merged the support for the new API

https://github.com/paolorechia/learn-langchain/pull/14

Readme section: https://github.com/paolorechia/learn-langchain#option-1---text-generation-webui-new-on-30042023

I hope it's useful for you :)

**Comment by paolorechia** [comment]
Happy to hear that you like it!

It’s actually cool for me too, since now I can play with more model
parameters :)

Thanks a lot for the suggestion

TestUser ***@***.***> schrieb am Di. 2. Mai 2023 um 12:06:
