### ISSUE TITLE
langchain autogpt examples without opeanai embeddings and faiss vector store

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#17]
So I appear to have the basic integration working with oobabooga, but i've been struggling a little bit with some of your agent examples.  I took a look at the langchain autogpt example here to see what some of the differences were:  https://python.langchain.com/en/latest/use_cases/autonomous_agents/autogpt.html

It does a few things differently than in your files, and it seems to not require the big prompt templates you are using.  I have yet to successfully get an of the example agents in this repo to do more complex things than a basic single instruct.  However, these examples are still tied to the openAI embeddings and openAI apis.  

I was trying to figure out how to take this example and convert it off of openai embeddings to use the sentence transformers and chroma for the memory.  These might be really really great examples to re-implement in your setup and show people how to use it with local models instead of all the openai stuff.

I'm kind of close to getting it to work?  I've tried porting your Chroma example over to replace the FAISS version, but I've mostly failed.

**Comment by paolorechia** [comment]
I built an example: https://github.com/paolorechia/learn-langchain/pull/18

It runs, but sadly the model performance is not good enough, e.g., the model gets stuck into non-sense. I don't think it's currently easy to run AutoGPT on local models. If you find a good way, please share. Otherwise, I'm closing the ticket.

**Comment by paolorechia** [comment]
Which one, auto GPT or my agents examples?

If you’re using the Zero Shot ReAct agent, one thing that really wrecks the
performance is not setting up the stop tokens correctly, it’s a bit hard to
debug, and has happened with me in the past. Any chance that you modified
it?


TestUser ***@***.***> schrieb am Mi. 3. Mai 2023 um 22:23:

**Comment by paolorechia** [comment]
Awesome, I’ll definitely check it out when I get some time :)

TestUser ***@***.***> schrieb am Fr. 5. Mai 2023 um 14:03:

**Comment by paolorechia** [comment]
Hi, what makes you think so?

It’s possible of course, do you think it could be on the output parsing?
You mentioned before it only works well for a single instruction, right?

TestUser ***@***.***> schrieb am Sa. 6. Mai 2023 um 13:23:
