### ISSUE TITLE
Load different models command on windows

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#6]
Really love the repo here and the approach you're taking.  I'm trying to get it to work and found one suggestion for your instructions.  Your command to use a different model returns an error if you try and run it on windows:

export USE_13B_MODEL=true && export USE_4BIT=true && uvicorn servers.vicuna_server:app

The export and && isn't supported.  I found that you can use the set command and format it like this:

set USE_13B_MODEL=true; set USE_4BIT=true;uvicorn servers.vicuna_server:app

**Comment by paolorechia** [comment]
Added these instructions to the README.md, thanks again.
