### ISSUE TITLE
error running 13b and 4bit

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#7]
Hi, so I'm really interested in trying out your new document qa example.  This is exactly what I was looking to prototype with a local llama model!  I have found that the 4bit quatized safetensor model loads and performs very quickly using the Oobabooga framework, and so I'm really excited to see that you're helping develop code that supports it outside of the UI.

However, when I try to run your server script with 4bit set to true and the 13b model flagged, i get an error that says "triton not installed" and then "No module named 'toml'".

I created a local venv for this project and ran the install requirements.  Could there be extra installation requirments for the gptq_for_llama code?

**Comment by paolorechia** [comment]
Hey, I've added instructions in the `README.md` and a short script to install all dependencies in Linux with pip. CUDA toolkit still needs to be installed manually, you can probably reuse a lot of the steps here, if you have not yet made it work on your end (except the bash commands).

Unfortunately, I can't add instructions for Windows, but feel free to open a PR if you figure it out.
