### ISSUE TITLE
vicuna_request_llm.py error  stop + ["Observation:"]

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#8]
I've modified your vicuna_chroma example to try and work with pdf documents.  To do this i've added in a load_qa_chain and passed in your VicunaLLM() as the model.  The pdf data was loading in properly, but then I kept getting an error when trying to call the model in the chain.  Here's what my code looks like:

chain = load_qa_chain(llm, chain_type="stuff")

query = "What is the title of this document"

docs = docsearch.similarity_search(query)

response = chain.run(input_documents=docs, question=query)

print(response)

and here's the error:

vicuna_request_llm.py", line 19, in _call
    "stop": stop + ["Observation:"],
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

If I comment out the "stop" parameter in that file, it actually works.  Any idea what I'm doing wrong?

Also, your setup is working quite well!  I'm able to run this locally on GPU and getting speedy response.

**Comment by paolorechia** [comment]
I’m not sure, skimming through your code my hunch is that the chain you used does not use a stop token?

My first impression is that my code does not support other chains for this reason, so maybe it should be fixed.

Glad to hear that you’re able to use the setup!

**Comment by paolorechia** [comment]
Should be fixed by commit:  https://github.com/paolorechia/learn-langchain/commit/d480a70ed0429235503ba5c5a7652929499e5032

Note: you might have to reinstall dependencies, as I have moved gptq_for_llama dependency to an outside fork repository.
